groupby + rolling

In [1]:
import pandas as pd

df = pd.DataFrame({
    "stock": ["TCS", "TCS", "TCS", "INFY", "INFY", "INFY"],
    "day": [1, 2, 3, 1, 2, 3],
    "price": [100, 110, 120, 200, 190, 210]
})

In [2]:
df.groupby('stock')['price'].rolling(2).mean().reset_index(level=0, drop=False)

  stock  price
3  INFY    NaN
4  INFY  195.0
5  INFY  200.0
0   TCS    NaN
1   TCS  105.0
2   TCS  115.0

In [3]:
df.groupby('stock')['price'].rolling(2).std().reset_index(level=0, drop=False)

  stock      price
3  INFY        NaN
4  INFY   7.071068
5  INFY  14.142136
0   TCS        NaN
1   TCS   7.071068
2   TCS   7.071068

In [4]:
df['price'].rolling(3).mean()

0           NaN
1           NaN
2    110.000000
3    143.333333
4    170.000000
5    200.000000
Name: price, dtype: float64

In [7]:
df['price'].rolling(3, min_periods=1).mean()

0    100.000000
1    105.000000
2    110.000000
3    143.333333
4    170.000000
5    200.000000
Name: price, dtype: float64

In [8]:
df['price'].rolling(3, min_periods=1).std()

0          NaN
1     7.071068
2    10.000000
3    49.328829
4    43.588989
5    10.000000
Name: price, dtype: float64

rolling().max(): rolling peak, e.g., 7‑day max temperature or 20‑day high in stock prices.

rolling().min(): rolling trough, e.g., lowest latency in last N samples or 20‑day low in prices.